<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>script_func</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\bridge\bridge.csproj" />
    <ProjectReference Include="..\client\client.csproj" />
    <ProjectReference Include="..\error\error.csproj" />
    <ProjectReference Include="..\func-router\func-router.csproj" />
    <ProjectReference Include="..\public-model\public-model.csproj" />
  </ItemGroup>

</Project>
